"""Reference copy of the user's standalone scheduler (source of truth for
the 236-student test dataset, block_ban_map, forbidden_course_groups, etc.).

This module is NOT used by the production arrange_courses tool — it only
provides the data needed to generate the realistic test CSVs in test_data/.
"""
from __future__ import annotations

import numpy as np
from collections import Counter, defaultdict
from typing import Dict, List, Tuple, Set
import random
import copy
import csv


def get_test_student_data() -> Dict[int, List[str]]:
    """236 students' full course selections (G11 + G12)."""
    return {
        1: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Economics", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        2: ["ELA 11", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Computer Science A", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        3: ["DP English A: Literature G11", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Computer Science A", "AP Seminar", "G11 Nationals"],
        4: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Economics", "AP Statistics", "AP Seminar", "G11 Nationals"],
        5: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Environmental Science", "Origins of Culture", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        6: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "AP Statistics", "AP Psychology", "AP Seminar AC", "G11 Nationals"],
        7: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Biology", "AP Seminar", "G11 Nationals"],
        8: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar", "G11 Nationals"],
        9: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Statistics", "AP Biology", "AP Seminar", "G11 Nationals"],
        10: ["DP English A: Literature G11", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        11: ["ELA 11 Honors", "DP Chinese A G11", "AP Calculus BC", "AP Psychology", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        12: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Environmental Science", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        13: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Accelerated Physics C", "AP Computer Science A", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        14: ["AP English Language and Composition", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Computer Science A", "AP Seminar AC", "G11 Nationals"],
        15: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Biology", "AP Macroeconomics", "AP Seminar AC", "G11 Nationals"],
        16: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Macroeconomics", "AP Seminar", "G11 Nationals"],
        17: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "AP Statistics", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        18: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Macroeconomics", "AP Microeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        19: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Statistics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        20: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "AP Chemistry", "DP Business Management G11", "AP Seminar AC", "G11 Nationals"],
        21: ["DP English A: Literature G11", "DP Chinese A G11", "AP Calculus BC", "Origins of Culture", "AP Statistics", "AP Seminar AC", "G11 Nationals"],
        22: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Environmental Science", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        23: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "Accelerated Physics C", "AP Chemistry", "AP Seminar AC", "G11 Nationals"],
        24: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Art and Design", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        25: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        26: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Environmental Science", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        27: ["AP English Language and Composition", "DP Chinese A G11", "Accelerated DP Math HL", "AP Environmental Science", "AP Chemistry", "AP Seminar AC", "G11 Nationals"],
        28: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        29: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Accelerated Economics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        30: ["ELA 11 Honors", "DP Chinese A G11", "AP Calculus BC", "DP Business Management G11", "AP Macroeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        31: ["DP English A: Literature G11", "DP Chinese A G11", "Accelerated DP Math HL", "AP Computer Science A", "AP Statistics", "AP Seminar AC", "G11 Nationals"],
        32: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Art and Design", "AP Seminar", "G11 Nationals"],
        33: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "AP Psychology", "Origins of Culture", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        34: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        35: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        36: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "AP Computer Science A", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        37: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Macroeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        38: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        39: ["DP English A: Literature G11", "Chinese G11", "AP Calculus BC", "AP Seminar", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        40: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Chemistry", "AP Seminar", "G11 Nationals"],
        41: ["DP English A: Literature G11", "DP Chinese A G11", "AP Calculus BC", "AP Seminar", "AP Macroeconomics", "AP Seminar", "G11 Nationals"],
        42: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        43: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        44: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        45: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Microeconomics", "AP Seminar", "G11 Nationals"],
        46: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        47: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Physics C: Mechanics", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        48: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Origins of Culture", "AP Macroeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        49: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Microeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        50: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Biology", "AP Seminar", "G11 Nationals"],
        51: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Economics", "AP Psychology", "AP Seminar", "G11 Nationals"],
        52: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        53: ["ELA 11", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Computer Science A", "AP Seminar", "G11 Nationals"],
        54: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Statistics", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        55: ["AP English Language and Composition", "Chinese G11", "Accelerated DP Math HL", "AP Statistics", "AP Computer Science A", "AP Seminar AC", "G11 Nationals"],
        56: ["ELA 11", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Computer Science A", "AP Seminar", "G11 Nationals"],
        57: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Environmental Science", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        58: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "Accelerated Physics C", "AP Chemistry", "AP Seminar", "G11 Nationals"],
        59: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Statistics", "Accelerated Economics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        60: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        61: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "Accelerated Economics", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        62: ["ELA 11", "Chinese G11", "AP Calculus BC", "Accelerated Economics", "DP Business Management G11", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        63: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Computer Science Principles", "AP Psychology", "AP Seminar", "G11 Nationals"],
        64: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Physics C: Mechanics", "Accelerated Economics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        65: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Environmental Science", "AP Seminar", "G11 Nationals"],
        66: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Statistics", "AP Computer Science A", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        67: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Statistics", "AP Environmental Science", "AP Seminar", "G11 Nationals"],
        68: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Computer Science A", "AP Seminar AC", "G11 Nationals"],
        69: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        70: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Statistics", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        71: ["DP English A: Literature G11", "DP Chinese A G11", "Accelerated DP Math HL", "AP Biology", "Accelerated Physics C", "AP Seminar AC", "G11 Nationals"],
        72: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Statistics", "AP Computer Science A", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        73: ["ELA 11 Honors", "DP Chinese A G11", "AP Calculus BC", "AP Psychology", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        74: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Environmental Science", "AP Physics C: Mechanics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        75: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Macroeconomics", "AP Statistics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        76: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "Accelerated Physics C", "Accelerated Economics", "AP Seminar", "G11 Nationals"],
        77: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Environmental Science", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        78: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Environmental Science", "AP Seminar AC", "G11 Nationals"],
        79: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Statistics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        80: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Psychology", "AP Seminar", "G11 Nationals"],
        81: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        82: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        83: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Art and Design", "AP Macroeconomics", "AP Seminar", "G11 Nationals"],
        84: ["ELA 11 Honors", "DP Chinese A G11", "Accelerated DP Math HL", "AP Accelerated Physics C", "AP Statistics", "AP Seminar", "G11 Nationals"],
        85: ["DP English A: Literature G11", "DP Chinese A G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Statistics", "AP Seminar AC", "G11 Nationals"],
        86: ["DP English A: Literature G11", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar", "G11 Nationals"],
        87: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Psychology", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        88: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Macroeconomics", "AP Statistics", "AP Seminar", "G11 Nationals"],
        89: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "AP Statistics", "DP Business Management G11", "AP Seminar", "G11 Nationals"],
        90: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Statistics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        91: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Statistics", "Accelerated Economics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        92: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Accelerated Economics", "Origins of Culture", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        93: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Microeconomics", "AP Statistics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        94: ["DP English A: Literature G11", "Chinese G11", "Accelerated DP Math HL", "AP Accelerated Physics C", "AP Accelerated Economics", "AP Seminar AC", "G11 Nationals"],
        95: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Psychology", "Origins of Culture", "AP Seminar", "G11 Nationals"],
        96: ["AP English Language and Composition", "DP Chinese A G11", "Accelerated DP Math HL", "DP Music G11", "AP Physics C: Mechanics", "AP Seminar AC", "G11 Nationals"],
        97: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "Origins of Culture", "AP Environmental Science", "AP Seminar", "G11 Nationals"],
        98: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Microeconomics", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        99: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Computer Science Principles", "DP Music G11", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        100: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "DP Music G11", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        101: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "Origins of Culture", "AP Environmental Science", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        102: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Psychology", "AP Biology", "AP Seminar", "G11 Nationals"],
        103: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Physics C: Mechanics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        104: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Biology", "AP Art and Design", "AP Seminar", "G11 Nationals"],
        105: ["ELA 11 Honors", "DP Chinese A G11", "AP Calculus BC", "Origins of Culture", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        106: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Biology", "AP Environmental Science", "AP Seminar AC", "G11 Nationals"],
        107: ["ELA 11", "DP Chinese A G11", "AP Calculus BC", "AP Macroeconomics", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        108: ["AP English Language and Composition", "DP Chinese A G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar AC", "G11 Nationals"],
        109: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Accelerated Economics", "AP Psychology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        110: ["ELA 11", "Chinese G11", "AP Calculus BC", "Origins of Culture", "Accelerated Economics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        111: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Statistics", "AP Microeconomics", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        112: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Biology", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        113: ["AP English Language and Composition", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        114: ["ELA 11 Honors", "DP Chinese A G11", "AP Calculus BC", "Accelerated Economics", "AP Computer Science A", "AP Seminar", "G11 Nationals"],
        115: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Environmental Science", "Origins of Culture", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        116: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Accelerated Economics", "AP Computer Science Principles", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        117: ["ELA 11 Honors", "Chinese G11", "AP Calculus BC", "AP Statistics", "DP Business Management G11", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        118: ["ELA 11", "Chinese G11", "AP Calculus BC", "Accelerated Physics C", "AP Chemistry", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        119: ["ELA 11", "Chinese G11", "AP Calculus BC", "AP Chemistry", "AP Biology", "AP Seminar", "G11 Nationals"],
        120: ["ELA 11 Honors", "Chinese G11", "Accelerated DP Math HL", "Accelerated Physics C", "AP Computer Science A", "Interdisciplinary Studies(IDS)", "G11 Nationals"],
        121: ["Further English: Literature & Performance", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Statistics", "AP Computer Science A", "AP Macroeconomics", "Chinese 12"],
        122: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Environmental Science", "Further Economics", "AP Statistics", "Chinese 12"],
        123: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "AP Statistics", "AP Computer Science Principles", "Introduction to Cognitive Science (Further Psychology)", "AP Research", "DP Chinese A G12"],
        124: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Statistics", "AP Computer Science A", "AP Chemistry", "AP Psychology", "Chinese 12"],
        125: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "Further Economics", "AP Psychology", "AP Music Theory", "AP Computer Science Principles", "Chinese 12"],
        126: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Environmental Science", "Origins of Culture", "Further Economics", "Chinese 12"],
        127: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "Further Economics", "AP Psychology", "AP Environmental Science", "Origins of Culture", "Chinese 12"],
        128: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Statistics", "AP Psychology", "AP Environmental Science", "Further Economics", "Chinese 12"],
        129: ["DP English A: Literature G12", "Maths 12: Math modeling", "AP Research", "AP Music Theory", "AP Computer Science Principles", "DP Chinese A G12"],
        130: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Psychology", "AP Music Theory", "Further Economics", "Chinese 12"],
        131: ["AP English Language and Composition G12", "DP Math HL G12", "Further Physics", "AP Chemistry", "AP Computer Science A", "AP Microeconomics", "Chinese 12"],
        132: ["Further English: Literature & Performance", "Maths 12: Spatial analytic geometry", "AP Computer Science Principles", "AP Psychology", "AP Macroeconomics", "AP Computer Science A", "Chinese 12"],
        133: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "AP Microeconomics", "Origins of Culture", "Chinese 12"],
        134: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "AP Art and Design", "AP Macroeconomics", "AP Psychology", "Chinese 12"],
        135: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "Origins of Culture", "Further Economics", "AP Computer Science A", "Introduction to Cognitive Science (Further Psychology)", "Chinese 12"],
        136: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "Further Economics", "Origins of Culture", "AP Statistics", "Chinese 12"],
        137: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Statistics", "AP Environmental Science", "Introduction to Cognitive Science (Further Psychology)", "AP Microeconomics", "Chinese 12"],
        138: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Environmental Science", "AP Psychology", "AP Physics C: Mechanics", "AP Physics C: Electricity & Magnetism", "Chinese 12"],
        139: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Environmental Science", "AP Psychology", "AP Physics C: Mechanics", "AP Physics C: Electricity & Magnetism", "Chinese 12"],
        140: ["AP English Literature and Composition", "Maths 12: Math modeling", "Further Economics", "Introduction to Cognitive Science (Further Psychology)", "AP Art and Design", "AP Research", "DP Chinese A G12"],
        141: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Chemistry", "AP Physics C: Mechanics", "AP Psychology", "AP Music Theory", "Chinese 12"],
        142: ["AP English Language and Composition G12", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "Origins of Culture", "AP Computer Science A", "AP Art and Design", "Chinese 12"],
        143: ["AP English Language and Composition G12", "DP Math HL G12", "Further Physics", "Origins of Culture", "AP Computer Science Principles", "Chinese 12"],
        144: ["AP English Literature and Composition", "Maths 12: Spatial analytic geometry", "Further Physics", "Origins of Culture", "AP Music Theory", "AP Research", "Chinese 12"],
        145: ["AP English Literature and Composition", "DP Math HL G12", "AP Research", "AP Statistics", "AP Biology", "DP Chinese A G12"],
        146: ["ELA 12", "Maths 12: Spatial analytic geometry", "AP Environmental Science", "AP Macroeconomics", "AP Environmental Science", "Chinese 12"],
        147: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "AP Research", "AP Psychology", "AP Art and Design", "Origins of Culture", "DP Chinese A G12"],
        148: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "Further Economics", "AP Statistics", "AP Research", "Further English: Literature Philosophy & the Meaning of Life", "DP Chinese A G12"],
        149: ["Further English: Literature & Performance", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Computer Science A", "AP Environmental Science", "AP Physics C: Mechanics", "Chinese 12"],
        150: ["Further English: Literature & Performance", "Maths 12: Math modeling", "AP Biology", "AP Macroeconomics", "AP Computer Science A", "AP Psychology", "Chinese 12"],
        151: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "Origins of Culture", "AP Computer Science A", "AP Research", "Chinese 12"],
        152: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Computer Science A", "Further Economics", "AP Physics C: Mechanics", "AP Research", "Chinese 12"],
        153: ["Further English: Literature & Performance", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "Origins of Culture", "Further Economics", "Chinese 12"],
        154: ["AP English Literature and Composition", "Maths 12: Spatial analytic geometry", "Origins of Culture", "AP Environmental Science", "AP Macroeconomics", "Chinese 12"],
        155: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "Further Physics", "AP Computer Science Principles", "AP Chemistry", "AP Psychology", "Chinese 12"],
        156: ["AP English Literature and Composition", "Maths 12: Math modeling", "AP Environmental Science", "Further Economics", "AP Computer Science A", "AP Art and Design", "Chinese 12"],
        157: ["AP English Literature and Composition", "Maths 12: Spatial analytic geometry", "AP Biology", "AP Statistics", "AP Macroeconomics", "Chinese 12"],
        158: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "AP Computer Science A", "AP Art and Design", "AP Physics C: Electricity & Magnetism", "Chinese 12"],
        159: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "Further Economics", "AP Statistics", "AP Computer Science Principles", "AP Research", "DP Chinese A G12"],
        160: ["ELA 12", "DP Math HL G12", "Further Economics", "AP Computer Science A", "AP Physics C: Mechanics", "Chinese 12"],
        161: ["AP English Literature and Composition", "Maths 12: Spatial analytic geometry", "Further Physics", "Origins of Culture", "AP Music Theory", "Further Economics", "Chinese 12"],
        162: ["DP English A: Literature G12", "Maths 12: Math modeling", "AP Environmental Science", "AP Statistics", "AP Research", "Further English: Literature Philosophy & the Meaning of Life", "Chinese 12"],
        163: ["DP English A: Literature G12", "Maths 12: Math modeling", "AP Art and Design", "AP Environmental Science", "AP Psychology", "AP Research", "DP Chinese A G12"],
        164: ["DP English A: Literature G12", "Maths 12: Math modeling", "AP Environmental Science", "AP Computer Science A", "AP Statistics", "Further Economics", "Chinese 12"],
        165: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Research", "AP Computer Science A", "AP Physics C: Electricity & Magnetism", "Origins of Culture", "DP Chinese A G12"],
        166: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Physics C: Mechanics", "AP Psychology", "AP Research", "AP Computer Science A", "Chinese 12"],
        167: ["ELA 12", "Maths 12: Math modeling", "AP Physics C: Mechanics", "AP Computer Science A", "AP Psychology", "AP Music Theory", "Chinese 12"],
        168: ["Further English: Literature & Performance", "Maths 12: Spatial analytic geometry", "AP Computer Science A", "Further Physics", "AP Macroeconomics", "AP Research", "DP Chinese A G12"],
        169: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Spatial analytic geometry", "AP Music Theory", "AP Research", "AP Macroeconomics", "Further Physics", "Chinese 12"],
        170: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Computer Science A", "Further Economics", "AP Environmental Science", "Chinese 12"],
        171: ["ELA 12", "Maths 12: Math modeling", "AP Art and Design", "AP Environmental Science", "AP Computer Science A", "Chinese 12"],
        172: ["AP English Literature and Composition", "Maths 12: Math modeling", "Further Economics", "AP Environmental Science", "Origins of Culture", "Chinese 12"],
        173: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "Further Economics", "AP Environmental Science", "AP Computer Science A", "Chinese 12"],
        174: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "AP Statistics", "AP Biology", "AP Computer Science A", "Chinese 12"],
        175: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Statistics", "AP Chemistry", "AP Computer Science A", "AP Art and Design", "Chinese 12"],
        176: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "AP Computer Science Principles", "AP Music Theory", "AP Art and Design", "Further Economics", "Chinese 12"],
        177: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "AP Statistics", "AP Environmental Science", "AP Biology", "Chinese 12"],
        178: ["AP English Literature and Composition", "DP Math HL G12", "AP Chemistry", "AP Microeconomics", "AP Macroeconomics", "AP Music Theory", "DP Chinese A G12"],
        179: ["DP English A: Literature G12", "Maths 12: Math modeling", "AP Psychology", "AP Research", "Further Economics", "Further English: Literature Philosophy & the Meaning of Life", "DP Chinese A G12"],
        180: ["AP English Literature and Composition", "Maths 12: Math modeling", "AP Psychology", "AP Computer Science Principles", "AP Environmental Science", "AP Research", "DP Chinese A G12"],
        181: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "AP Psychology", "AP Environmental Science", "AP Chemistry", "Chinese 12"],
        182: ["Further English: Literature & Performance", "Maths 12: Math modeling", "AP Environmental Science", "AP Psychology", "AP Art and Design", "Chinese 12"],
        183: ["ELA 12", "Maths 12: Math modeling", "AP Environmental Science", "AP Computer Science A", "Further Economics", "Chinese 12"],
        184: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Macroeconomics", "AP Computer Science A", "AP Art and Design", "AP Psychology", "Chinese 12"],
        185: ["ELA 12", "Maths 12: Math modeling", "AP Environmental Science", "AP Macroeconomics", "AP Statistics", "Chinese 12"],
        186: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "AP Research", "Introduction to Cognitive Science (Further Psychology)", "AP Environmental Science", "AP Art and Design", "DP Chinese A G12"],
        187: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "AP Chemistry", "Further Physics", "AP Computer Science A", "AP Psychology", "Chinese 12"],
        188: ["AP English Literature and Composition", "Maths 12: Math modeling", "AP Biology", "AP Physics C: Mechanics", "AP Computer Science A", "AP Statistics", "Chinese 12"],
        189: ["ELA 12", "Maths 12: Spatial analytic geometry", "AP Psychology", "Further Economics", "Origins of Culture", "AP Computer Science A", "Chinese 12"],
        190: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Art and Design", "AP Environmental Science", "AP Computer Science A", "Chinese 12"],
        191: ["ELA 12", "Maths 12: Math modeling", "AP Psychology", "Further Economics", "AP Art and Design", "Chinese 12"],
        192: ["Further English: Literature & Performance", "DP Math HL G12", "AP Research", "Further Economics", "AP Physics C: Electricity & Magnetism", "AP Psychology", "Chinese 12"],
        193: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "Further Economics", "AP Computer Science A", "AP Computer Science Principles", "AP Physics C: Electricity & Magnetism", "Chinese 12"],
        194: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Psychology", "AP Computer Science A", "AP Environmental Science", "Chinese 12"],
        195: ["Further English: Literature & Performance", "DP Math HL G12", "Further Physics", "AP Chemistry", "AP Computer Science A", "AP Research", "Chinese 12"],
        196: ["ELA 12", "Maths 12: Math modeling", "AP Environmental Science", "Further Economics", "AP Computer Science A", "AP Chemistry", "Chinese 12"],
        197: ["AP English Language and Composition G12", "Maths 12: Math modeling", "AP Psychology", "AP Environmental Science", "AP Art and Design", "AP Computer Science A", "Chinese 12"],
        198: ["AP English Literature and Composition", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Biology", "AP Environmental Science", "Origins of Culture", "Chinese 12"],
        199: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Environmental Science", "Further Physics", "AP Computer Science A", "Origins of Culture", "Chinese 12"],
        200: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Physics C: Electricity & Magnetism", "Further Physics", "AP Computer Science A", "AP Computer Science Principles", "Chinese 12"],
        201: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Computer Science A", "AP Environmental Science", "Chinese 12"],
        202: ["Further English: Literature & Performance", "Maths 12: Spatial analytic geometry", "Further Physics", "AP Statistics", "AP Chemistry", "Further Economics", "Chinese 12"],
        203: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Art and Design", "AP Environmental Science", "AP Computer Science Principles", "Chinese 12"],
        204: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Music Theory", "AP Microeconomics", "AP Computer Science A", "Chinese 12"],
        205: ["ELA 12", "Maths 12: Spatial analytic geometry", "Further Physics", "AP Statistics", "Origins of Culture", "AP Macroeconomics", "Chinese 12"],
        206: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Art and Design", "Further Economics", "Introduction to Cognitive Science (Further Psychology)", "Chinese 12"],
        207: ["ELA 12 Honors: Language & Rhetoric", "DP Math HL G12", "AP Chemistry", "AP Statistics", "AP Microeconomics", "Chinese 12"],
        208: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "AP Psychology", "AP Art and Design", "AP Macroeconomics", "AP Chemistry", "Chinese 12"],
        209: ["AP English Literature and Composition", "Maths 12: Spatial analytic geometry", "Further Physics", "Origins of Culture", "AP Music Theory", "AP Research", "Chinese 12"],
        210: ["ELA 12", "Maths 12: Spatial analytic geometry", "AP Macroeconomics", "AP Physics C: Electricity & Magnetism", "AP Computer Science Principles", "AP Chemistry", "Chinese 12"],
        211: ["AP English Literature and Composition", "Maths 12: Math modeling", "AP Computer Science A", "Further Economics", "AP Music Theory", "Introduction to Cognitive Science (Further Psychology)", "DP Chinese A G12"],
        212: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Microeconomics", "AP Psychology", "AP Environmental Science", "AP Art and Design", "Chinese 12"],
        213: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Biology", "AP Macroeconomics", "AP Computer Science A", "AP Physics C: Mechanics", "Chinese 12"],
        214: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Spatial analytic geometry", "AP Environmental Science", "AP Statistics", "AP Microeconomics", "AP Macroeconomics", "Chinese 12"],
        215: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "AP Music Theory", "AP Psychology", "AP Macroeconomics", "AP Computer Science Principles", "Chinese 12"],
        216: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Chemistry", "AP Psychology", "AP Computer Science A", "AP Art and Design", "Chinese 12"],
        217: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "AP Chemistry", "AP Computer Science A", "Further Physics", "AP Microeconomics", "Chinese 12"],
        218: ["Further English: Literature Philosophy & the Meaning of Life", "Maths 12: Math modeling", "Introduction to Cognitive Science (Further Psychology)", "AP Computer Science A", "AP Art and Design", "AP Research", "DP Chinese A G12"],
        219: ["Further English: Literature & Performance", "Maths 12: Math modeling", "AP Psychology", "Further Economics", "AP Computer Science Principles", "AP Music Theory", "Chinese 12"],
        220: ["ELA 12", "Maths 12: Math modeling", "AP Chemistry", "AP Psychology", "AP Statistics", "Chinese 12"],
        221: ["Further English: Literature & Performance", "Maths 12: Math modeling", "Further Economics", "Origins of Culture", "AP Research", "AP Computer Science A", "Chinese 12"],
        222: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Math modeling", "AP Art and Design", "AP Macroeconomics", "AP Environmental Science", "Chinese 12"],
        223: ["Further English: Literature & Performance", "Maths 12: Math modeling", "AP Art and Design", "AP Psychology", "AP Research", "AP Macroeconomics", "DP Chinese A G12"],
        224: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Computer Science A", "AP Computer Science Principles", "AP Psychology", "AP Biology", "Chinese 12"],
        225: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "Introduction to Cognitive Science (Further Psychology)", "AP Chemistry", "AP Statistics", "AP Art and Design", "Chinese 12"],
        226: ["Further English: Literature Philosophy & the Meaning of Life", "DP Math HL G12", "AP Research", "Origins of Culture", "Introduction to Cognitive Science (Further Psychology)", "Further English: Literature Philosophy & the Meaning of Life", "DP Chinese A G12"],
        227: ["ELA 12 Honors: The Artist's Voice", "Maths 12: Spatial analytic geometry", "Further Physics", "AP Statistics", "Origins of Culture", "AP Computer Science Principles", "Chinese 12"],
        228: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Computer Science A", "AP Physics C: Mechanics", "AP Research", "Introduction to Cognitive Science (Further Psychology)", "Chinese 12"],
        229: ["ELA 12", "Maths 12: Math modeling", "AP Environmental Science", "AP Computer Science A", "Further Economics", "Chinese 12"],
        230: ["ELA 12 Honors: Language & Rhetoric", "Maths 12: Math modeling", "AP Chemistry", "AP Biology", "AP Computer Science A", "Chinese 12"],
        231: ["ELA 12", "Maths 12: Spatial analytic geometry", "Further Physics", "AP Macroeconomics", "AP Computer Science A", "AP Computer Science Principles", "Chinese 12"],
        232: ["Further English: Literature & Performance", "Maths 12: Math modeling", "AP Physics C: Mechanics", "AP Computer Science A", "AP Psychology", "AP Art and Design", "Chinese 12"],
        233: ["AP English Language and Composition G12", "Maths 12: Spatial analytic geometry", "AP Art and Design", "AP Psychology", "AP Environmental Science", "AP Statistics", "Chinese 12"],
        234: ["AP English Language and Composition G12", "Maths 12: Math modeling", "Further Economics", "AP Computer Science A", "AP Environmental Science", "Chinese 12"],
        235: ["AP English Literature and Composition", "Maths 12: Math modeling", "AP Psychology", "AP Biology", "AP Research", "AP Art and Design", "Chinese 12"],
        236: ["ELA 12", "Maths 12: Math modeling", "AP Macroeconomics", "AP Art and Design", "AP Computer Science Principles", "Chinese 12"],
    }


def get_custom_sections() -> Dict[str, int]:
    """Section counts for every course in the dataset."""
    return {
        "ELA 12 Honors: Language & Rhetoric": 2,
        "Maths 12: Spatial analytic geometry": 2,
        "AP Statistics": 3,
        "AP Psychology": 4,
        "AP Environmental Science": 3,
        "Further Economics": 1,
        "Chinese 12": 5,
        "Maths 12: Math modeling": 3,
        "AP Chemistry": 2,
        "AP Biology": 3,
        "AP Computer Science A": 3,
        "ELA 12 Honors: The Artist's Voice": 1,
        "AP Art and Design": 2,
        "AP Macroeconomics": 2,
        "Introduction to Cognitive Science (Further Psychology)": 1,
        "AP Music Theory": 1,
        "AP Microeconomics": 1,
        "AP English Literature and Composition": 1,
        "AP English Language and Composition": 2,
        "AP English Language and Composition G12": 1,
        "DP Math HL G12": 1,
        "Further Physics": 1,
        "Further English: Literature Philosophy & the Meaning of Life": 1,
        "AP Physics C: Electricity & Magnetism": 1,
        "AP Computer Science Principles": 2,
        "Further English: Literature & Performance": 1,
        "AP Research": 2,
        "DP Chinese A G12": 1,
        "Origins of Culture": 3,
        "ELA 12": 1,
        "AP Physics C: Mechanics": 1,
        "DP English A: Literature G12": 1,
        "ELA 11 Honors": 3,
        "DP Chinese A G11": 1,
        "Accelerated DP Math HL 11": 1,
        "Accelerated Physics C": 1,
        "AP Seminar": 1,
        "AP Seminar AC": 1,
        "G11 Nationals": 5,
        "Chinese G11": 4,
        "AP Calculus BC": 5,
        "ELA 11": 2,
        "Interdisciplinary Studies(IDS)": 2,
        "DP English A: Literature G11": 1,
        "Accelerated Economics": 1,
        "DP Business Management G11": 1,
        "DP Music G11": 1,
        "Further English: Narration & Journalism": 1,
    }


def get_block_ban_map() -> Dict[str, Set[int]]:
    """Slot-level bans per course."""
    return {
        "AP Calculus BC": {4, 1},
        "AP Statistics": {4, 1},
        "Maths 12: Spatial analytic geometry": {4, 1},
        "Maths 12: Math modeling": {4, 1},
        "DP Math HL G12": {4, 1},
        "Accelerated DP Math HL 11": {4, 1},
        "AP Art and Design": {0, 3, 6},
        "AP Computer Science A": {4, 0, 2},
        "AP Computer Science Principles": {4, 0, 2},
    }


def get_forbidden_course_groups() -> Set[Tuple[str, ...]]:
    """Course-tuples that should NOT share a slot."""
    return {
        ("Accelerated Economics", "Interdisciplinary Studies(IDS)"),
        ("Interdisciplinary Studies(IDS)", "AP Seminar", "AP Seminar AC"),
        ("DP English A: Literature G12", "Further English: Literature Philosophy & the Meaning of Life"),
        ("DP English A: Literature G11", "Further English: Literature Philosophy & the Meaning of Life"),
    }


def get_course_name_remap() -> Dict[str, str]:
    """Aliases in the raw student data that must be normalized."""
    return {
        "DP English A: Literature": "DP English A – Literature",
        "AP English Languagae and Composition": "AP English Language and Composition",
        "Accelerated DP Math HL": "Accelerated DP Math HL 11",
    }


def get_num_time_slots() -> int:
    return 7


def get_max_iterations() -> int:
    return 20000


def get_thresholds() -> Dict[str, int]:
    return {
        "min_students_threshold": 25,
        "max_students_threshold": 65,
        "min_students_per_section": 12,
        "max_students_per_section": 30,
    }
